on: pull_request

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ludeeus/action-shellcheck@master
        with:
          severity: style
  shellspec:
    name: shellspec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
         sudo apt-get install -y git=1:2.25.1-1ubuntu3.2
         git --version
         curl -fsSL https://git.io/shellspec | sh -s -- --yes
         ${HOME}/.local/bin/shellspec -x --log-file log.txt || cat log.txt
